code = """

# PYTHON: autogenerated runtime code
import re
import traceback
import json

# context
# define some context here (e.g. types for arguments)
class Node():
    next_node = None
    prev_node = None

# initial code
# function should have name 'main'
def main():
    pass

# assertions
result = {
    'errors': [],
    'passed': 0,
    'failed': 0
}
try:
    assert main() == 42
except AssertionError:
    error = str(traceback.format_exc())
    error = re.sub(r'".*?"', '***', error)

    result['failed'] += 1
    result['errors'].append(error)
else:
    result['passed'] += 1

print(json.dumps(result))
"""


from tempfile import NamedTemporaryFile
import os

scriptFile = NamedTemporaryFile(delete=True, suffix=".py")
with open(scriptFile.name, "w") as f:
    f.write(code)
    os.chmod(scriptFile.name, 777)

os.system(f"python {scriptFile.name}")
