"""empty message

Revision ID: d2b4053beafd
Revises: c18b5570ef4a
Create Date: 2024-03-10 12:33:31.952210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d2b4053beafd"
down_revision = "c18b5570ef4a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("picture", sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "picture")
    # ### end Alembic commands ###
