"""empty message

Revision ID: b4c1a8528291
Revises: 102ce12cbb98
Create Date: 2024-04-07 17:40:20.081972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4c1a8528291'
down_revision = '102ce12cbb98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('problems_categories_problem_id_fkey', 'problems_categories', type_='foreignkey')
    op.drop_constraint('problems_categories_category_id_fkey', 'problems_categories', type_='foreignkey')
    op.create_foreign_key(None, 'problems_categories', 'problems', ['problem_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'problems_categories', 'pcategories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problems_categories', type_='foreignkey')
    op.drop_constraint(None, 'problems_categories', type_='foreignkey')
    op.create_foreign_key('problems_categories_category_id_fkey', 'problems_categories', 'pcategories', ['category_id'], ['id'])
    op.create_foreign_key('problems_categories_problem_id_fkey', 'problems_categories', 'problems', ['problem_id'], ['id'])
    # ### end Alembic commands ###
