"""empty message

Revision ID: 8fef0d94a47b
Revises: 02f2e9e7aec0
Create Date: 2024-03-24 15:03:24.842514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '8fef0d94a47b'
down_revision = '02f2e9e7aec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    problem_lang_status = postgresql.ENUM('active', 'disabled', name='problemlangstatus')
    problem_lang_status.create(op.get_bind())
    op.add_column('lang_problems', sa.Column('status', sa.Enum('active', 'disabled', name='problemlangstatus'), server_default='disabled', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lang_problems', 'status')
    problem_lang_status = postgresql.ENUM('active', 'disabled', name='problemlangstatus')
    problem_lang_status.drop(op.get_bind())
    # ### end Alembic commands ###
