"""empty message

Revision ID: 02f2e9e7aec0
Revises: d2b4053beafd
Create Date: 2024-03-10 16:12:46.681083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02f2e9e7aec0'
down_revision = 'd2b4053beafd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lang_problems', 'status')
    op.add_column('problems', sa.Column('status', sa.Enum('active', 'disabled', name='problemstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'status')
    op.add_column('lang_problems', sa.Column('status', postgresql.ENUM('active', 'disabled', name='problemstatus'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
