"""empty message

Revision ID: 72ae980d18b6
Revises: 1d0b969eece3
Create Date: 2024-04-14 18:16:45.189173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ae980d18b6'
down_revision = '1d0b969eece3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runtimes', sa.Column('tests_passed', sa.Integer(), nullable=True))
    op.add_column('runtimes', sa.Column('tests_failed', sa.Integer(), nullable=True))
    op.add_column('runtimes', sa.Column('finish_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('runtimes', 'seconds_passed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runtimes', sa.Column('seconds_passed', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('runtimes', 'finish_date')
    op.drop_column('runtimes', 'tests_failed')
    op.drop_column('runtimes', 'tests_passed')
    # ### end Alembic commands ###
