"""empty message

Revision ID: 7cb22327ae54
Revises: 1b830eae4f65
Create Date: 2024-04-20 14:56:58.025705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb22327ae54'
down_revision = '1b830eae4f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('room_uid', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'room_uid')
    # ### end Alembic commands ###
