"""empty message

Revision ID: 1d0b969eece3
Revises: bf8938aeebb1
Create Date: 2024-04-14 16:32:19.279614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1d0b969eece3"
down_revision = "bf8938aeebb1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("runtimes", sa.Column("code", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runtimes", "code")
    # ### end Alembic commands ###
