"""empty message

Revision ID: 1b830eae4f65
Revises: 72ae980d18b6
Create Date: 2024-04-17 21:21:41.427685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b830eae4f65'
down_revision = '72ae980d18b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runtimes', sa.Column('output', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runtimes', 'output')
    # ### end Alembic commands ###
